apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:   
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{
      "type": "public",
      "bandwidth_name": "cce-bandwidth-1551163379627",
      "bandwidth_chargemode": "bandwidth",
      "bandwidth_size": 5,
      "bandwidth_sharetype": "PER",
      "eip_type": "5_bgp"
    }'
    kubernetes.io/elb.enterpriseID: '0'  # Replace '0' if you have an enterprise project ID
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: service0
    protocol: TCP
    port: 80
    targetPort: 80